config/routes.rb
TireMart::Application.routes.draw do
  get 'products',     to: 'products#index', as: 'products'
  get 'products/new', to: 'products#new', as: 'new_product'
  get 'products/:id', to: 'products#show', as:'product'
  post 'products',    to: 'products#create' 
  get 'products/:id/edit', to: 'products#edit', as: 'edit_product'
  patch 'products/:id', to: 'products#update'
  delete 'products/:id', to: 'products#destroy', as: 'delete_product'

 

  root 'products#index'

end

app/models/customer.rb
class Customer < ActiveRecord::Base
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
	validates :name, :price, :stock_quantity, presence: true
	validates :price, numericality: {greater_than_or_equal_to: 0.01}
	validates :stock_quantity, numericality: {only_integer: true}
end

app/models/province.rb
class Province < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end
  # Loads up the view of the same name after the atction has executed 
  # app/views/products/index.html.erb

  def show
    @product = Product.find(params[:id])
  end# Loads: apps/views/products/new.html.erb

  def new
     @product = Product.new
  end # We either redirect or render the new view

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to action: :index
    else
      render :new
    end
  end# Either redirect or render the new view

  def edit
    @product = Product.find(params[:id])
  end# Loads: app/views/products/edit.html.erb

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(product_params)
      redirect_to @product
    else
      render :edit
    end
  end# Either redirect or render the edit view 

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to root_path
  end# Always redirect to the root after we have deleted

  private
    def product_params
      params.require(:product).permit(:name, :price, :description,:stock_quantity,:image_filename)
    end
end 

app/controllers/provinces_controller.rb
class ProvincesController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/provinces_helper.rb
module ProvincesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TireMart</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'shared/header' %>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
	<% if @product.errors.any? %>
		<p> There were <%= pluralize @product.errors.count, 'error' %>   that prevented your product from being added</p>
		<ul>
			<% @product.errors.full_messages.each do |msg| %>
			<li><%= msg %> </li>
			<% end %>
		</ul>
	<% end %>
	<div>
		<%= f.label :name %>
		<br>
		<%= f.text_field :name %>
	</div>
	<div>
		<%= f.label :price %>
		<br>
		<%= f.text_field :price %>
	</div>
	<div>
		<%= f.label :description %>
		<br>
		<%= f.text_area :description %>
	</div>
	<div>
		<%= f.label :stock_quantity %>
		<br>
		<%= f.text_field :stock_quantity %>
	</div>
	<div>
		<%= f.label :image_filename %>
		<br>
		<%= f.text_field :image_filename %>
	</div>
	<div>
		<%= f.submit %>
	</div>
<% end %>

app/views/products/_product.html.erb
<section>
	<h3><%= link_to product.name, product %></h3>

	<% if product.image_filename.present? %>
	<p>
		<%= image_tag product.image_filename %>
	</p>
	<% end %>
	
	<p><%= product.description %></p>
	<p><strong>Price:</strong> <%= number_to_currency product.price %></p>
	<p><strong>Stock Quantity </strong> <%= number_to_human product.stock_quantity %></p>
	<p><%= link_to 'edit', edit_product_path(product) %>
	   <%= link_to 'delete', delete_product_path(product), method: :delete, confirm: "Are you sure you want to delete this product?" %>
	</p>
	<hr>
</section>

app/views/products/edit.html.erb
<h1>Products#edit</h1>

<%= render 'form' %>

app/views/products/index.html.erb
<h1>All Products</h1>

<p><%= link_to 'New Product',new_product_path %></p>

<%= render @products %>

app/views/products/new.html.erb
<h1>New Product</h1>


<%= render 'form' %>

app/views/products/show.html.erb
<%= render @product %>
<p><%= link_to 'Home', root_path %></p>

app/views/provinces/edit.html.erb
<h1>Provinces#edit</h1>
<p>Find me in app/views/provinces/edit.html.erb</p>

app/views/provinces/index.html.erb
<h1>Provinces#index</h1>
<p>Find me in app/views/provinces/index.html.erb</p>

app/views/provinces/new.html.erb
<h1>Provinces#new</h1>
<p>Find me in app/views/provinces/new.html.erb</p>

app/views/provinces/show.html.erb
<h1>Provinces#show</h1>
<p>Find me in app/views/provinces/show.html.erb</p>

app/views/shared/_header.html.erb
<header>
	<h1>TireMart Store</h1>
</header>

app/views/welcome/index.html.erb
<h1>Tire Mart Products</h1>

<h2> index </h2>